---
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  vars_prompt:
    - name: Packages
      prompt: What packages would you like to install?
      private: no
  tasks:
    - name: Install packege
      yum: 
        name: "{{Packages}}"
        state: installed
      
